/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {},
    colors: {
      black: "#000000",
      white: "#ffffff",
      cream: "#ECDCDF",
      violet: "#AC98BD",
      "violet-dark": "#9967c0",
      gray: "#CABBD8",
      "light-blue": "#7F8CC0",
      green: "#B6DAD0",
      purple: "#82446B",
      yelow: "#FAE46C",
      orange: "#F4AF2D",
    },
    fontSize: {
      sm: "0.875rem",
      base: "1rem",
      lg: "1.125rem",
      xl: "1.25rem",
      "2xl": "1.5rem",
      "3xl": "1.875rem",
      "4xl": "2.25rem",
      "5xl": "3rem",
      "6xl": "4rem",
      "7xl": "5rem",
      "8xl": "6rem",
      "9xl": "8rem",
    },
  },
  plugins: [],
};
